Cleaned up mixins
fedpol1/enchantips pull request #10
Opened 2024-12-31 18:03 UTC by tyrannus00

The main objective of this pr is to improve mod compatibility, by getting rid of some invasive `@Redirect`s and `@Overwrite`s. These cause crashes when another mod tries to mixin to the same place. I got rid of all occurences, except for 2 `@Redirect`s, because their replacements would require some very brittle Localcaptures, and the redirects in those places actually make sense imo.
I also generally cleaned up the mixins to be more concise and contain less unnecessary code.

2025-01-12 02:35 UTC, fedpol1 requested changes

2025-01-12 02:35 UTC, fedpol1 commented on src/main/java/com/fedpol1/enchantips/mixin/BundleTooltipComponentMixin.java
> +            SlotHighlight.highlightSingleSlot(drawContext, stack, x + 4, y + 4, 255);
This is ok under the assumption that other mods do not change the location of items in the bundle tooltip, however that is not an assumption I want to make. If the way this part of the mod is written currently leads to crashes, then so be it.

2025-01-12 02:35 UTC, fedpol1 commented on src/main/java/com/fedpol1/enchantips/mixin/ClientPlayNetworkHandlerMixin.java
> -public abstract class ClientPlayNetworkHandlerMixin {
All mixin classes should be abstract to prevent instantiating them since they are not supposed to be instantiated. Some of them not being abstract currently is a failure on my part.

2025-01-12 02:35 UTC, fedpol1 commented on src/main/java/com/fedpol1/enchantips/mixin/ClientPlayNetworkHandlerMixin.java
> -    private void enchantips$registerPerEnchantmentConfig(MinecraftClient client, ClientConnection clientConnection, ClientConnectionState clientConnectionState, CallbackInfo ci) {
What is the point of this?

2025-01-12 02:35 UTC, fedpol1 commented on src/main/java/com/fedpol1/enchantips/mixin/EnchantmentMixin.java
> +    @Inject(method = "getName", at = @At("HEAD"), cancellable = true)
Unconditionally cancelled injects are worse for compatibility than overwrites since they do not inform the user there is an incompatibility; one of the mods will just seemingly for no reason not work. Producing a crash here is preferred.

2025-01-12 02:35 UTC, fedpol1 commented on src/main/java/com/fedpol1/enchantips/mixin/EnchantmentScreenHandlerMixin.java
> -    public void enchantips$setProperty(int id, int value, CallbackInfo ci) throws IllegalStateException {
Good catch.

2025-01-12 02:35 UTC, fedpol1 commented on src/main/java/com/fedpol1/enchantips/mixin/UnbreakableComponentMixin.java
> +    @Inject(method = "appendTooltip", at = @At(value = "INVOKE", target = "Ljava/util/function/Consumer;accept(Ljava/lang/Object;)V"), cancellable = true)
This should be an overwrite.

2025-01-12 02:35 UTC, fedpol1 commented on src/main/java/com/fedpol1/enchantips/mixin/ItemEnchantmentsComponentMixin.java
> +    @Inject(method = "appendTooltip", at = @At("HEAD"), cancellable = true)
This should be an overwrite.

2025-01-12 02:35 UTC, fedpol1 commented on src/main/java/com/fedpol1/enchantips/mixin/ItemStackMixin.java
> +    @Override
These are not overrides.

2025-01-13 07:48 UTC, tyrannus00 commented on src/main/java/com/fedpol1/enchantips/mixin/UnbreakableComponentMixin.java
> +    @Inject(method = "appendTooltip", at = @At(value = "INVOKE", target = "Ljava/util/function/Consumer;accept(Ljava/lang/Object;)V"), cancellable = true)
I opened the pr mostly because of this change, as this was the mixin which was conflicting with another mod I am using. I understand the point you make about Overwrites being prefered so the mixin doesn't fail silently, however, the user will see which tooltip gets applied, so they can figure themselves that one of multiple mods, which modify the same parts of the code, will take priority. For this reason (at least in my opinion) compatibility through an Inject is preferable here, even though you are technically correct.
If you agree I will adjust the pr to account for the other requested changes, if not, thats fine, and I will close it, but feel free to implement the other changes you agreed with on your own then.

2025-08-22 09:37 UTC, closed without merging